In [1]:
import pandas as pd
import pandera as pa

In [19]:
valores_ausentes = ['##!', '####', '****', '*****', '**', 'NULL']
df = pd.read_csv('ocorrencia_2010_2020.csv', parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes) 
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03 00:00:00,12:00:00,0.0
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03 00:00:00,11:05:00,0.0
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2021-07-23 03:00:00,3:00:00,0.0
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04 00:00:00,17:30:00,0.0
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05 00:00:00,19:25:00,0.0
5,39807.0,39807.0,INCIDENTE,SALVADOR,BA,NaN,2010-01-06 00:00:00,17:53:00,0.0
6,40215.0,40215.0,INCIDENTE,COARI,AM,SBUY,2010-01-07 00:00:00,18:40:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09 00:00:00,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10 00:00:00,23:15:00,2.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10 00:00:00,20:00:00,0.0

In [20]:
schema = pa.DataFrameSchema(
    columns = {
        'codigo_ocorrencia':pa.Column(pa.Int, nullable=True),
        'codigo_ocorrencia2':pa.Column(pa.Int, nullable=True),
        'ocorrencia_classificacao':pa.Column(pa.String, nullable=True),
        'ocorrencia_cidade':pa.Column(pa.String, nullable=True), # nullable = True: permite que a coluna receba valores nulos.
        'ocorrencia_uf':pa.Column(pa.String, pa.Check.str_length(2, 2), nullable=True), # pa.Check.str_length(2, 2): Difini o min e o máx de caracteres aceitos nesta coluna
        'ocorrencia_aerodromo':pa.Column(pa.String, nullable=True),
        'ocorrencia_dia':pa.Column(pa.DateTime, nullable=True),
        'ocorrencia_hora':pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        'total_recomendacoes':pa.Column(pa.Float, nullable=True)
    }
)

In [21]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03 00:00:00,12:00:00,0.0
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03 00:00:00,11:05:00,0.0
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2021-07-23 03:00:00,3:00:00,0.0
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04 00:00:00,17:30:00,0.0
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05 00:00:00,19:25:00,0.0
...,...,...,...,...,...,...,...,...,...
5748,79757.0,79757.0,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30 00:00:00,18:30:00,0.0
5749,79802.0,79802.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30 00:00:00,0:54:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31 00:00:00,9:00:00,0.0
5751,79844.0,79844.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31 00:00:00,13:24:00,0.0
5752,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [22]:
df.dtypes

codigo_ocorrencia                  float64
codigo_ocorrencia2                 float64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
dtype: object

In [23]:
df.loc[1]

codigo_ocorrencia                       40349.0
codigo_ocorrencia2                      40349.0
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELÉM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                         0.0
Name: 1, dtype: object

In [24]:
df.iloc[1]

codigo_ocorrencia                       40349.0
codigo_ocorrencia2                      40349.0
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELÉM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                         0.0
Name: 1, dtype: object

In [33]:
df.drop(5752, inplace=True)

In [34]:
df.iloc[-1]

codigo_ocorrencia                       79844.0
codigo_ocorrencia2                      79844.0
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                RIO DE JANEIRO
ocorrencia_uf                                RJ
ocorrencia_aerodromo                       SBJR
ocorrencia_dia              2020-12-31 00:00:00
ocorrencia_hora                        13:24:00
total_recomendacoes                         0.0
Name: 5751, dtype: object

In [35]:
df.tail()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0
5748,79757.0,79757.0,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5749,79802.0,79802.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,0:54:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,9:00:00,0.0
5751,79844.0,79844.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0.0

In [36]:
df.iloc[10:15] # consulta realizada através do índice

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789.0,39789.0,INCIDENTE,SÃO PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0.0
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
12,40414.0,40414.0,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,3:00:00,0.0
13,39507.0,39507.0,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0
14,40107.0,40107.0,ACIDENTE,GURUPÁ,PA,SNGU,2010-01-12,14:30:00,0.0

In [37]:
df.loc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789.0,39789.0,INCIDENTE,SÃO PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0.0
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
12,40414.0,40414.0,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,3:00:00,0.0
13,39507.0,39507.0,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0
14,40107.0,40107.0,ACIDENTE,GURUPÁ,PA,SNGU,2010-01-12,14:30:00,0.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0

In [40]:
df.loc[:,'ocorrencia_uf']

0       RJ
1       PA
2       RJ
3       MT
4       RS
        ..
5747    SP
5748    TO
5749    RJ
5750    MS
5751    RJ
Name: ocorrencia_uf, Length: 5752, dtype: object

In [41]:
df['ocorrencia_uf']

0       RJ
1       PA
2       RJ
3       MT
4       RS
        ..
5747    SP
5748    TO
5749    RJ
5750    MS
5751    RJ
Name: ocorrencia_uf, Length: 5752, dtype: object

In [43]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade             11
ocorrencia_uf                 12
ocorrencia_aerodromo        2349
ocorrencia_dia                11
ocorrencia_hora               12
total_recomendacoes           11
dtype: int64

In [44]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade             11
ocorrencia_uf                 12
ocorrencia_aerodromo        2349
ocorrencia_dia                11
ocorrencia_hora               12
total_recomendacoes           11
dtype: int64

In [51]:
filtro = df.ocorrencia_uf.isnull() # filtra quais são as linhas que possuem valor NaN na coluna ocorrencia_uf
df.loc[filtro] # lista o filtro

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2227,49474.0,49474.0,ACIDENTE,ÁGUAS INTERNACIONAIS,NaN,NaN,2013-09-02,2:54:00,0.0
2920,52697.0,52697.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
2987,52948.0,52948.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4459,79567.0,79567.0,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
4491,78035.0,78035.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4700,78324.0,78324.0,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5472,79385.0,79385.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5514,79445.0,79445.0,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5544,79481.0,79481.0,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5624,79582.0,79582.0,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5664,79663.0,79663.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5735,79799.0,79799.0,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [52]:
filtro = df.ocorrencia_aerodromo.isnull() 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
5,39807.0,39807.0,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5741,79754.0,79754.0,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0.0
5744,79753.0,79753.0,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5745,79755.0,79755.0,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0.0
5748,79757.0,79757.0,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,9:00:00,0.0

In [53]:
filtro = df.ocorrencia_hora.isnull() 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2920,52697.0,52697.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
2987,52948.0,52948.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4100,78823.0,78823.0,INCIDENTE,CORUMBÁ,MS,NaN,2017-07-09,NaN,0.0
4459,79567.0,79567.0,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
4491,78035.0,78035.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4700,78324.0,78324.0,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5472,79385.0,79385.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5514,79445.0,79445.0,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5544,79481.0,79481.0,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5624,79582.0,79582.0,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5664,79663.0,79663.0,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5735,79799.0,79799.0,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [54]:
df.count()

codigo_ocorrencia           5752
codigo_ocorrencia2          5752
ocorrencia_classificacao    5752
ocorrencia_cidade           5741
ocorrencia_uf               5740
ocorrencia_aerodromo        3403
ocorrencia_dia              5741
ocorrencia_hora             5740
total_recomendacoes         5741
dtype: int64

In [58]:
# ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
63,39992.0,39992.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-02-17,20:07:00,11.0
326,42250.0,42250.0,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19.0
530,43471.0,43471.0,ACIDENTE,SÃO PAULO,SP,NaN,2010-12-14,20:15:00,11.0
727,44377.0,44377.0,ACIDENTE,ITÁPOLIS,SP,SDIO,2011-04-09,14:50:00,11.0
872,44796.0,44796.0,ACIDENTE,RECIFE,PE,SBRF,2011-07-13,9:54:00,23.0
884,44888.0,44888.0,INCIDENTE GRAVE,SÃO JOSÉ DOS PINHAIS,PR,SBCT,2011-07-15,17:05:00,11.0
1062,45554.0,45554.0,INCIDENTE GRAVE,UBERLÂNDIA,MG,SBUL,2011-11-15,2:15:00,20.0
1972,47938.0,47938.0,INCIDENTE,BRASÍLIA,DF,SBBR,2013-04-13,18:00:00,11.0
2795,52265.0,52265.0,ACIDENTE,SANTOS,SP,NaN,2014-08-13,13:03:00,13.0
3930,66432.0,66432.0,INCIDENTE GRAVE,VITÓRIA,ES,NaN,2017-02-21,11:47:00,12.0

In [60]:
# ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade', 'total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
63               SÃO PAULO                 11.0
326         RIO DE JANEIRO                 19.0
530              SÃO PAULO                 11.0
727               ITÁPOLIS                 11.0
872                 RECIFE                 23.0
884   SÃO JOSÉ DOS PINHAIS                 11.0
1062            UBERLÂNDIA                 20.0
1972              BRASÍLIA                 11.0
2795                SANTOS                 13.0
3930               VITÓRIA                 12.0

In [61]:
# ocorrências com classificação = INCIDENTE GRAVE
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro, ['ocorrencia_cidade', 'ocorrencia_classificacao']]

      ocorrencia_cidade ocorrencia_classificacao
7              CANUTAMA          INCIDENTE GRAVE
8              CASCAVEL          INCIDENTE GRAVE
9         PARÁ DE MINAS          INCIDENTE GRAVE
29             CURITIBA          INCIDENTE GRAVE
35               PALMAS          INCIDENTE GRAVE
...                 ...                      ...
5741       NOVA MARINGÁ          INCIDENTE GRAVE
5744           GOIATUBA          INCIDENTE GRAVE
5746      MANOEL URBANO          INCIDENTE GRAVE
5748  LAGOA DA CONFUSÃO          INCIDENTE GRAVE
5750          VICENTINA          INCIDENTE GRAVE

[737 rows x 2 columns]

In [67]:
# ocorrências com classificação = INCIDENTE GRAVE no estado de SP
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
136,40270.0,40270.0,INCIDENTE GRAVE,PIRASSUNUNGA,SP,SDPY,2010-04-15,20:15:00,0.0
171,40620.0,40620.0,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2010-05-06,15:50:00,0.0
219,41411.0,41411.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-06-08,19:30:00,2.0
297,42289.0,42289.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-07-29,20:06:00,0.0
314,42323.0,42323.0,INCIDENTE GRAVE,SÃO JOSÉ DO RIO PRETO,SP,SBSR,2010-08-05,12:01:00,0.0
...,...,...,...,...,...,...,...,...,...
5591,79540.0,79540.0,INCIDENTE GRAVE,SÃO PAULO,SP,NaN,2020-09-12,13:10:00,0.0
5610,79566.0,79566.0,INCIDENTE GRAVE,REGENTE FEIJÓ,SP,SDYJ,2020-09-27,19:33:00,0.0
5704,79739.0,79739.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705.0,79705.0,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718.0,79718.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0

In [68]:
# ocorrências com classificação = INCIDENTE GRAVE ou o estado é SP
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5744,79753.0,79753.0,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5746,79769.0,79769.0,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0
5748,79757.0,79757.0,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,9:00:00,0.0

In [83]:
# ocorrências com classificação = INCIDENTE GRAVE ou classificação = INCIDENTE e o estado é SP
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE']) # .isin é uma melhor maneira de substituir o | (OR)
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
18,39828.0,39828.0,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0.0
26,39847.0,39847.0,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
27,39768.0,39768.0,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0.0
33,39848.0,39848.0,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0.0
...,...,...,...,...,...,...,...,...,...
5704,79739.0,79739.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705.0,79705.0,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718.0,79718.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0
5742,79800.0,79800.0,INCIDENTE,SÃO PAULO,SP,SBMT,2020-12-28,10:15:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [84]:
# ocorrências cuja CIDADE comecem com a letra C
filtro = df.ocorrencia_cidade.str[0] == 'C' 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215.0,40215.0,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
20,40310.0,40310.0,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0.0
...,...,...,...,...,...,...,...,...,...
5661,79649.0,79649.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0.0
5663,79652.0,79652.0,INCIDENTE,CONFINS,MG,SBCF,2020-11-06,14:20:00,0.0
5680,79683.0,79683.0,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2020-11-16,22:00:00,0.0
5696,79692.0,79692.0,ACIDENTE,CATANDUVA,SP,SDCD,2020-11-28,12:50:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [85]:
# ocorrências cuja CIDADE terminem com a letra A
filtro = df.ocorrencia_cidade.str[-1] == 'A' 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
12,40414.0,40414.0,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,3:00:00,0.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
25,39772.0,39772.0,INCIDENTE,UBERLÂNDIA,MG,NaN,2010-01-20,18:58:00,0.0
26,39847.0,39847.0,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
...,...,...,...,...,...,...,...,...,...
5738,79787.0,79787.0,INCIDENTE,FORTALEZA,CE,SBFZ,2020-12-23,18:30:00,0.0
5739,79749.0,79749.0,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0.0
5743,79824.0,79824.0,ACIDENTE,RIO PARANAÍBA,MG,SNRP,2020-12-28,17:00:00,0.0
5744,79753.0,79753.0,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,9:00:00,0.0

In [86]:
# ocorrências cuja CIDADE terminem com os caracteres MA
filtro = df.ocorrencia_cidade.str[-2:] == 'MA' 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
408,43062.0,43062.0,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1.0
688,44198.0,44198.0,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0.0
1035,51785.0,51785.0,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0.0
1377,45939.0,45939.0,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0.0
1401,46180.0,46180.0,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0.0
2099,49113.0,49113.0,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4.0
2102,48799.0,48799.0,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0.0
2655,51347.0,51347.0,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0.0
2855,52340.0,52340.0,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1.0
2966,52832.0,52832.0,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0.0
2997,52979.0,52979.0,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0.0
3040,52984.0,52984.0,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0.0
3092,53596.0,53596.0,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0.0
3157,53223.0,53223.0,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0.0
3171,53265.0,53265.0,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2.0
3189,53271.0,53271.0,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0.0
3682,65414.0,65414.0,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1.0
3725,65633.0,65633.0,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0.0
3881,66265.0,66265.0,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0.0
4229,77371.0,77371.0,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1.0
4311,77612.0,77612.0,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0.0
4574,78080.0,78080.0,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0.0
4986,78867.0,78867.0,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,0:00:00,0.0
5070,78923.0,78923.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0.0
5080,78782.0,78782.0,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0.0
5405,79282.0,79282.0,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0.0
5440,79338.0,79338.0,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,9:40:00,0.0
5474,79400.0,79400.0,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0.0

In [90]:
# ocorrências cuja CIDADE contém com os caracteres MA
filtro = df.ocorrencia_cidade.str.contains('MA|AL', na=False) 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,39807.0,39807.0,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
13,39507.0,39507.0,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
17,39810.0,39810.0,INCIDENTE,SALVADOR,BA,NaN,2010-01-15,18:23:00,0.0
...,...,...,...,...,...,...,...,...,...
5738,79787.0,79787.0,INCIDENTE,FORTALEZA,CE,SBFZ,2020-12-23,18:30:00,0.0
5739,79749.0,79749.0,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0.0
5741,79754.0,79754.0,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0.0
5745,79755.0,79755.0,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0.0
5746,79769.0,79769.0,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0

In [92]:
# ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015 # dt: utilizado para acessar parte da DATA. 
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2996,52992.0,52992.0,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3.0
2997,52979.0,52979.0,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0.0
2998,53073.0,53073.0,INCIDENTE,TEFÉ,AM,SBTF,2015-01-02,16:28:00,0.0
2999,53074.0,53074.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0.0
3000,52976.0,52976.0,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6.0
...,...,...,...,...,...,...,...,...,...
3462,60632.0,60632.0,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0.0
3463,60600.0,60600.0,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0.0
3464,60642.0,60642.0,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0.0
3465,60631.0,60631.0,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2.0
3466,60649.0,60649.0,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0.0

In [91]:
df.dtypes

codigo_ocorrencia                  float64
codigo_ocorrencia2                 float64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
dtype: object

In [101]:
# ocorrências do ano de 2015, mês 12 e dia 8
filtroAno = df.ocorrencia_dia.dt.year == 2015
filtroMes = df.ocorrencia_dia.dt.month == 12
filtroDia = df.ocorrencia_dia.dt.day == 8 # dt: utilizado para acessar parte da DATA. 
df.loc[filtroAno & filtroMes & filtroDia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0

In [107]:
# ocorrências do ano de 2015, mês 12 e entre os dias 8 e 13
filtroAno = df.ocorrencia_dia.dt.year == 2015
filtroMes = df.ocorrencia_dia.dt.month == 12
filtroDia = (df.ocorrencia_dia.dt.day > 2) & (df.ocorrencia_dia.dt.day < 9)   # dt: utilizado para acessar parte da DATA.
df.loc[filtroAno & filtroMes & filtroDia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3432,53575.0,53575.0,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0

In [112]:
df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora

0       2010-01-03 00:00:00 12:00:00
1       2010-01-03 00:00:00 11:05:00
2        2021-07-23 03:00:00 3:00:00
3       2010-01-04 00:00:00 17:30:00
4       2010-01-05 00:00:00 19:25:00
                    ...
5747    2020-12-29 00:00:00 19:00:00
5748    2020-12-30 00:00:00 18:30:00
5749     2020-12-30 00:00:00 0:54:00
5750     2020-12-31 00:00:00 9:00:00
5751    2020-12-31 00:00:00 13:24:00
Length: 5752, dtype: object

In [117]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

In [119]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03 00:00:00,12:00:00,0.0,2010-01-03 12:00:00
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03 00:00:00,11:05:00,0.0,2010-01-03 11:05:00
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2021-07-23 03:00:00,3:00:00,0.0,2021-07-23 03:00:00
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04 00:00:00,17:30:00,0.0,2010-01-04 17:30:00
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05 00:00:00,19:25:00,0.0,2010-01-05 19:25:00

In [120]:
df.dtypes

codigo_ocorrencia                  float64
codigo_ocorrencia2                 float64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [121]:
# ocorrências do ano de 2015, mês 12 e entre os dias 8 e 13
filtroAno = df.ocorrencia_dia_hora.dt.year == 2015
filtroMes = df.ocorrencia_dia_hora.dt.month == 12
filtroDia = (df.ocorrencia_dia_hora.dt.day > 2) & (df.ocorrencia_dia_hora.dt.day < 9)   # dt: utilizado para acessar parte da DATA.
df.loc[filtroAno & filtroMes & filtroDia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3432,53575.0,53575.0,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0,2015-12-03 10:50:00
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,2015-12-03 16:47:00
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,2015-12-06 13:10:00
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,2015-12-06 15:00:00
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,2015-12-08 14:30:00
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,2015-12-08 10:20:00
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,2015-12-08 16:19:00
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,2015-12-08 13:00:00

In [124]:
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 14:30:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,2015-12-03 16:47:00
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,2015-12-06 13:10:00
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,2015-12-06 15:00:00
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,2015-12-08 14:30:00
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,2015-12-08 10:20:00
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,2015-12-08 13:00:00

In [126]:
# ocorrências do ano de 2015 e mês 3
filtro1 = df.ocorrencia_dia.dt.year == 2015 # dt: utilizado para acessar parte da DATA. 
filtro2 = df.ocorrencia_dia.dt.month == 3
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3086,53183.0,53183.0,ACIDENTE,AMAPORÃ,PR,NaN,2015-03-02,23:00:00,0.0,2015-03-02 23:00:00
3087,53120.0,53120.0,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0.0,2015-03-04 13:30:00
3088,53109.0,53109.0,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0.0,2015-03-05 13:50:00
3089,53112.0,53112.0,ACIDENTE,MOGI GUAÇU,SP,NaN,2015-03-06,21:00:00,0.0,2015-03-06 21:00:00
3090,53152.0,53152.0,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2.0,2015-03-10 11:30:00
3091,53167.0,53167.0,INCIDENTE,MARABÁ,PA,SBMA,2015-03-10,17:33:00,0.0,2015-03-10 17:33:00
3092,53596.0,53596.0,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0.0,2015-03-10 21:35:00
3093,53149.0,53149.0,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0.0,2015-03-11 23:25:00
3094,53148.0,53148.0,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0.0,2015-03-12 12:40:00
3095,53153.0,53153.0,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0.0,2015-03-13 15:45:00
3096,53154.0,53154.0,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0.0,2015-03-13 14:40:00
3097,53238.0,53238.0,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0.0,2015-03-13 11:30:00
3098,53189.0,53189.0,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,7:20:00,0.0,2015-03-14 07:20:00
3099,53193.0,53193.0,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0.0,2015-03-14 18:00:00
3100,53164.0,53164.0,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0.0,2015-03-15 18:30:00
3101,53151.0,53151.0,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1.0,2015-03-16 18:07:00
3102,53168.0,53168.0,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0.0,2015-03-16 21:05:00
3103,53169.0,53169.0,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,3:25:00,0.0,2015-03-19 03:25:00
3104,53165.0,53165.0,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,NaN,2015-03-20,14:35:00,0.0,2015-03-20 14:35:00
3105,53188.0,53188.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0.0,2015-03-20 21:00:00
3106,53184.0,53184.0,ACIDENTE,PORTO UNIÃO,SC,NaN,2015-03-22,13:44:00,0.0,2015-03-22 13:44:00
3107,53178.0,53178.0,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0.0,2015-03-23 17:15:00
3108,53182.0,53182.0,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0.0,2015-03-23 20:40:00
3109,53166.0,53166.0,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0.0,2015-03-24 14:45:00
3110,53170.0,53170.0,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0.0,2015-03-24 17:57:00
3111,53185.0,53185.0,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0.0,2015-03-24 23:01:00
3112,53412.0,53412.0,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2015-03-24,16:35:00,0.0,2015-03-24 16:35:00
3113,53194.0,53194.0,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0.0,2015-03-26 20:30:00
3114,53186.0,53186.0,INCIDENTE,BRASÍLIA,DF,NaN,2015-03-27,14:55:00,0.0,2015-03-27 14:55:00
3115,53179.0,53179.0,ACIDENTE,CAIAPÔNIA,GO,NaN,2015-03-28,10:30:00,0.0,2015-03-28 10:30:00
3116,53180.0,53180.0,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0.0,2015-03-28 18:52:00
3117,53190.0,53190.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0.0,2015-03-28 16:26:00
3118,53212.0,53212.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0.0,2015-03-28 17:32:00
3119,53213.0,53213.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0.0,2015-03-28 15:51:00
3120,53181.0,53181.0,ACIDENTE,COLÍDER,MT,NaN,2015-03-29,20:17:00,0.0,2015-03-29 20:17:00
3121,53187.0,53187.0,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0.0,2015-03-29 18:36:00
3122,53211.0,53211.0,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0.0,2015-03-30 19:40:00

In [128]:
df201503.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [131]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count() # correto, pois a coluna codigo_ocorrencia considera os valores NULL

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [133]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count() #errado, pois pela coluna .ocorrencia_aerodromo não é considerado os valores NULL

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [135]:
df201503.groupby(['ocorrencia_classificacao']).size() # correto, o método size() permite a contagem de todos os registros, inclusive os NULL

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [136]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values() # lista em ordem crescente

ocorrencia_classificacao
INCIDENTE GRAVE     5
ACIDENTE           15
INCIDENTE          17
dtype: int64

In [137]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False) # lista em ordem decrescente

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [141]:
filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP', 'MG', 'ES', 'RJ'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0,2010-01-03 12:00:00
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0,2010-01-10 20:00:00
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0,2010-01-10 14:50:00
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0,2010-01-15 15:00:00
18,39828.0,39828.0,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0.0,2010-01-15 17:45:00
...,...,...,...,...,...,...,...,...,...,...
541,43722.0,43722.0,ACIDENTE,CAJOBI,SP,NaN,2010-12-23,11:00:00,0.0,2010-12-23 11:00:00
544,43548.0,43548.0,INCIDENTE,SÃO PAULO,SP,SBSP,2010-12-26,22:10:00,0.0,2010-12-26 22:10:00
548,43724.0,43724.0,ACIDENTE,COSMÓPOLIS,SP,NaN,2010-12-29,12:00:00,0.0,2010-12-29 12:00:00
550,43730.0,43730.0,INCIDENTE,VITÓRIA,ES,NaN,2010-12-30,18:10:00,0.0,2010-12-30 18:10:00
551,43975.0,43975.0,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0.0,2010-12-30 14:28:00

In [142]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            40
INCIDENTE          169
INCIDENTE GRAVE     18
dtype: int64

In [145]:
dfsudeste2010.count()

codigo_ocorrencia           227
codigo_ocorrencia2          227
ocorrencia_classificacao    227
ocorrencia_cidade           227
ocorrencia_uf               227
ocorrencia_aerodromo        126
ocorrencia_dia              227
ocorrencia_hora             227
total_recomendacoes         227
ocorrencia_dia_hora         227
dtype: int64

In [149]:
dfsudeste2010.groupby(['ocorrencia_classificacao', 'ocorrencia_uf']).size()

ocorrencia_classificacao  ocorrencia_uf
ACIDENTE                  MG                7
                          RJ                9
                          SP               24
INCIDENTE                 ES                5
                          MG               39
                          RJ               51
                          SP               74
INCIDENTE GRAVE           MG                5
                          RJ                4
                          SP                9
dtype: int64

In [150]:
dfsudeste2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
RIO DE JANEIRO           46
SÃO PAULO                33
GUARULHOS                18
BELO HORIZONTE           17
CAMPINAS                 13
MACAÉ                    12
CONFINS                   7
UBERLÂNDIA                5
JUIZ DE FORA              4
VITÓRIA                   4
MARÍLIA                   3
SÃO JOSÉ DOS CAMPOS       3
SÃO JOSÉ DO RIO PRETO     3
SOROCABA                  2
ITANHAÉM                  2
RIBEIRÃO PRETO            2
IPATINGA                  2
POÇOS DE CALDAS           2
DIVINÓPOLIS               2
BAURU                     2
JUNDIAÍ                   2
ARARAQUARA                2
CAMPOS DOS GOYTACAZES     2
AREALVA                   2
MONTES CLAROS             2
UBERABA                   2
POUSO ALEGRE              1
PIRACICABA                1
PIRASSUNUNGA              1
ARRAIAL DO CABO           1
RESENDE                   1
PENÁPOLIS                 1
SANTOS                    1
SERRA NEGRA               1
SÃO BERNARDO DO CAMPO     1
TIMÓTEO                   1
ARAÇATUBA                 1
PIACATU                   1
BOM JESUS DO AMPARO       1
PARÁ DE MINAS             1
OLÍMPIA                   1
BRAGANÇA PAULISTA         1
BROTAS                    1
CAJOBI                    1
CAMANDUCAIA               1
BOITUVA                   1
CASIMIRO DE ABREU         1
BOCAINA                   1
COROMANDEL                1
COSMÓPOLIS                1
DIAMANTINA                1
BEBEDOURO                 1
IPERÓ                     1
ITÁPOLIS                  1
LINHARES                  1
MANGARATIBA               1
BOM JESUS DO GALHO        1
NOVO HORIZONTE            1
AMERICANA                 1
dtype: int64

In [152]:
# somar o tanto de recomendações que o RIO DE JANEIRO teve
filtro = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro].total_recomendacoes.sum()

25.0

In [154]:
# somar o tanto de recomendações que o RIO DE JANEIRO teve
filtro1 = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
filtro2 = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
119,40190.0,40190.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,2:35:00,3.0,2010-04-06 02:35:00
274,41750.0,41750.0,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3.0,2010-07-12 19:53:00
326,42250.0,42250.0,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19.0,2010-08-12 12:26:00

In [158]:
dfsudeste2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0.0
ARARAQUARA                0.0
ARAÇATUBA                 0.0
AREALVA                   0.0
ARRAIAL DO CABO           0.0
BAURU                     0.0
BEBEDOURO                 0.0
BELO HORIZONTE            2.0
BOCAINA                   0.0
BOITUVA                   1.0
BOM JESUS DO AMPARO       0.0
BOM JESUS DO GALHO        1.0
BRAGANÇA PAULISTA         9.0
BROTAS                    0.0
CAJOBI                    0.0
CAMANDUCAIA               9.0
CAMPINAS                  0.0
CAMPOS DOS GOYTACAZES     0.0
CASIMIRO DE ABREU         0.0
CONFINS                   0.0
COROMANDEL                0.0
COSMÓPOLIS                0.0
DIAMANTINA                0.0
DIVINÓPOLIS               0.0
GUARULHOS                 0.0
IPATINGA                  0.0
IPERÓ                     3.0
ITANHAÉM                  1.0
ITÁPOLIS                  0.0
JUIZ DE FORA              0.0
JUNDIAÍ                   7.0
LINHARES                  0.0
MACAÉ                     0.0
MANGARATIBA               0.0
MARÍLIA                   0.0
MONTES CLAROS             0.0
NOVO HORIZONTE            3.0
OLÍMPIA                   0.0
PARÁ DE MINAS             0.0
PENÁPOLIS                 0.0
PIACATU                   0.0
PIRACICABA                0.0
PIRASSUNUNGA              0.0
POUSO ALEGRE              0.0
POÇOS DE CALDAS           0.0
RESENDE                   8.0
RIBEIRÃO PRETO            0.0
RIO DE JANEIRO           25.0
SANTOS                    0.0
SERRA NEGRA               0.0
SOROCABA                  0.0
SÃO BERNARDO DO CAMPO     2.0
SÃO JOSÉ DO RIO PRETO     0.0
SÃO JOSÉ DOS CAMPOS       0.0
SÃO PAULO                41.0
TIMÓTEO                   3.0
UBERABA                   0.0
UBERLÂNDIA                0.0
VITÓRIA                   0.0
Name: total_recomendacoes, dtype: float64

In [168]:
dfsudeste2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBAE     0.0
SBAQ     0.0
SBBH     0.0
SBBP     9.0
SBBU     0.0
SBCF     0.0
SBGL     3.0
SBGR     0.0
SBIP     0.0
SBJD     7.0
SBJR     3.0
SBKP     0.0
SBME     0.0
SBMK     0.0
SBML     0.0
SBMT    27.0
SBPC     0.0
SBPR     1.0
SBRJ    19.0
SBRP     0.0
SBSJ     0.0
SBSP     0.0
SBSR     0.0
SBUL     0.0
SBUR     0.0
SBVT     0.0
SDAM     0.0
SDOI     1.0
SDPW     0.0
SDPY     0.0
SNDT     0.0
SNDV     0.0
SNXT     0.0
NaN     45.0
Name: total_recomendacoes, dtype: float64

In [172]:
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
BOITUVA                   1.0
BOM JESUS DO GALHO        1.0
ITANHAÉM                  1.0
BELO HORIZONTE            2.0
SÃO BERNARDO DO CAMPO     2.0
IPERÓ                     3.0
NOVO HORIZONTE            3.0
TIMÓTEO                   3.0
JUNDIAÍ                   7.0
RESENDE                   8.0
BRAGANÇA PAULISTA         9.0
CAMANDUCAIA               9.0
RIO DE JANEIRO           25.0
SÃO PAULO                41.0
Name: total_recomendacoes, dtype: float64

In [175]:
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade', dfsudeste2010.ocorrencia_dia.dt.month]).total_recomendacoes.sum().sort_values()

ocorrencia_cidade      ocorrencia_dia
BELO HORIZONTE         2                  1.0
                       3                  1.0
BOITUVA                7                  1.0
BOM JESUS DO GALHO     12                 1.0
ITANHAÉM               9                  1.0
SÃO PAULO              6                  2.0
SÃO BERNARDO DO CAMPO  1                  2.0
JUNDIAÍ                6                  2.0
RIO DE JANEIRO         7                  3.0
                       4                  3.0
NOVO HORIZONTE         7                  3.0
IPERÓ                  1                  3.0
TIMÓTEO                2                  3.0
JUNDIAÍ                5                  5.0
SÃO PAULO              11                 6.0
RESENDE                4                  8.0
SÃO PAULO              1                  8.0
CAMANDUCAIA            7                  9.0
BRAGANÇA PAULISTA      11                 9.0
SÃO PAULO              12                11.0
                       2                 14.0
RIO DE JANEIRO         8                 19.0
Name: total_recomendacoes, dtype: float64

In [179]:
filtro1 = dfsudeste2010.total_recomendacoes > 0
filtro2 = dfsudeste2010.ocorrencia_cidade == 'SÃO PAULO'
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0,2010-01-10 14:50:00
58,39275.0,39275.0,ACIDENTE,SÃO PAULO,SP,NaN,2010-02-10,9:03:00,3.0,2010-02-10 09:03:00
63,39992.0,39992.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-02-17,20:07:00,11.0,2010-02-17 20:07:00
219,41411.0,41411.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-06-08,19:30:00,2.0,2010-06-08 19:30:00
469,43450.0,43450.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-11-04,10:55:00,6.0,2010-11-04 10:55:00
530,43471.0,43471.0,ACIDENTE,SÃO PAULO,SP,NaN,2010-12-14,20:15:00,11.0,2010-12-14 20:15:00